name: Deploy Sparqsys Site

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy source to deployment directory
        run: |
          sudo mkdir -p /home/server/sparqsys
          sudo find /home/server/sparqsys -mindepth 1 -delete
          sudo cp -r . /home/server/sparqsys
          sudo chown -R server:server /home/server/sparqsys

      - name: Install dependencies
        run: sudo /home/server/.nvm/versions/node/v22.14.0/bin/npm install
        working-directory: /home/server/sparqsys

      - name: Build the app
        run: sudo /home/server/.nvm/versions/node/v22.14.0/bin/npm run build
        working-directory: /home/server/sparqsys

      - name: Restart systemd service
        run: sudo systemctl restart sparqsys
