'use client'

import Link from "next/link"
import { useState } from "react"

interface TOSProps {
    isOpen?: boolean
}

export default function TOSDropdown({ isOpen }: TOSProps) {

    const [open, setOpen] = useState<boolean>(isOpen? true : false)

    return (
        <div className="w-full relative">
            {/* Dropdown menu button */}
            <div
                className={`p-4 cursor-pointer bg-gray-100 rounded-xl border hover:bg-gray-200 ${open? 'sticky top-[66px] z-10':''}`}
                onClick={() => setOpen(!open)}
                aria-expanded={open}
            >
                <div className="flex flex-row justify-between items-center">
                    <span>Terms of Service</span>
                    <svg
                        fill="#000000"
                        height="20"
                        width="20"
                        version="1.1"
                        id="Layer_1"
                        viewBox="0 0 330.00 330.00"
                        className={`transform transition-transform duration-300 ${open ? 'scale-y-[-1]' : ''
                            }`}
                    >
                        <path
                            id="XMLID_225_"
                            d="M325.607,79.393c-5.857-5.857-15.355-5.858-21.213,0.001l-139.39,139.393L25.607,79.393 c-5.857-5.857-15.355-5.858-21.213,0.001c-5.858,5.858-5.858,15.355,0,21.213l150.004,150c2.813,2.813,6.628,4.393,10.606,4.393 s7.794-1.581,10.606-4.394l149.996-150C331.465,94.749,331.465,85.251,325.607,79.393z"
                        />
                    </svg>
                </div>
            </div>
            {/* TOS content */}
            {open && (
                <div className="flex flex-col gap-4 sm:p-10 p-4 mt-2">
                    <h2 className="font-bold">Last Updated: January 30, 2025</h2>
                    <p>Please read these Terms of Service (“Terms”) carefully. Your purchase of Products or access to or use of the Services (each as defined below) constitutes your agreement to be bound by these Terms. Notwithstanding anything herein to the contrary, if a written contract signed by both parties is in existence covering the sale of the Products and Services covered hereby, the terms and conditions of such contract shall prevail to the extent they are inconsistent with these Terms.</p>
                    <p>These Terms are between you (“you”) and SPARQ Systems Inc. (“SPARQ”, “we” or “us”) concerning the sale of microinverters and other goods and products by SPARQ (“Products”) and your access and/or use of SPARQ&apos;s platform, including its websites and applications, and the content, information and services provided through such platform (collectively, the “Services”).</p>
                    <p>By purchasing Products, accessing or using the Services, or by installing, copying or downloading any software that comprises a Service (such as an application) or that is made available through any Service, you agree to be bound by the terms and conditions of these Terms. If you do not agree to the terms and conditions of these Terms, you must not purchase Products or use the Services. We may revise these Terms from time to time in our sole discretion and provide you with notice of such change by any reasonable means, including by making available the revised version of these Terms through the Services.  You should periodically visit this page to review the then-current version of the Terms. The “Last Updated” legend at the top of this page indicates when these Terms were last revised. Your purchase of Products or continued access to or use of the Services following any changes will signify your acceptance of such changes and your agreement to be bound by them.</p>
                    <p>These Terms together with any accompanying order form or confirmation of sale (the <b>“Sales Confirmation”</b>) comprise the entire agreement between the parties, and supersede all prior or contemporaneous understandings, agreements, negotiations, representations and warranties, and communications, both written and oral. These Terms prevail over any of your general terms and conditions of purchase regardless of whether or when you have submitted your purchase order or such terms. Fulfillment of your order does not constitute acceptance of any of your terms and conditions and does not serve to modify or amend these Terms.</p>
                    <h2 className="underline font-bold">PURCHASE THROUGH AUTHORIZED RESELLER OR DISTRIBUTOR</h2>
                    <p>You may acquire SPARQ Products and Services from an authorized reseller or distributor of SPARQ. In the event that you do so, you acknowledge and agree that: (i) to the extent applicable, these Terms will continue to apply to your purchase of Products or Services; (ii) your purchase will be subject to the reseller or distributor&apos;s, as the case may be, own terms and conditions (the “Reseller Terms”); (iii) the Reseller Terms are between you and the applicable reseller or distributor and are not binding on SPARQ; and (iv) any disputes related to the Reseller Terms shall be handled directly between you and the applicable reseller or distributor. In the event of any conflict between these Terms and the Reseller Terms, these Terms shall govern as between you and SPARQ.</p>
                    <h2 className="underline font-extrabold">TERMS APPLYING TO YOUR PURCHASE OF PRODUCTS</h2>
                    {/* terms list */}
                    <ol className="list-decimal">
                        <li><strong>Order Procedure</strong>.</li>
                        <ol className="list-inside list-[lower-alpha]">
                            <li>All offers and quotations of any kind received by you from SPARQ, in whatever form, are without commitment and may be revoked at any time.</li>
                            <li>You may make an offer to purchase the Products by submitting a purchase order to SPARQ under the terms and conditions of these Terms and on no other terms. Any variations made to these Terms by you in any purchase order are void and have no effect.</li>
                            <li>SPARQ has the right, in its sole discretion, to accept or reject any purchase order. SPARQ may accept any purchase order by confirming the order (whether by written confirmation, invoice, or otherwise) or by delivering such Products, whichever occurs first. No purchase order is binding on SPARQ unless accepted by SPARQ as provided in these Terms.</li>
                            <li>Notwithstanding anything to the contrary contained in these Terms, SPARQ reserves the right to make technical modifications and changes to the shape, colour, design, material and/or weight of the Products, provided that the quality and functionality of the Products is not materially altered as a result of the modifications. Without limiting the foregoing, SPARQ reserves the right to deliver Products of equivalent value or of a higher specification in place of those identified in the Sales Confirmation.</li>
                        </ol>
                        <li><strong>Delivery of Products</strong>.</li>
                        <ol className="list-inside list-[lower-alpha]">
                            <li>The Products will be delivered within a reasonable time after the receipt of your purchase order, subject to availability of finished Products. SPARQ shall not be liable for any delays, loss, or damage in transit.</li>
                            <li>Any time quoted by SPARQ for delivery is an estimate only. SPARQ is not liable for or in respect of any loss or damage arising from any delay in filling any order, failure to deliver or delay in delivery. No delay in the shipment or delivery of any Products relieves you of your obligations under these Terms, including accepting delivery of any remaining instalment(s) of Products.</li>
                            <li>Unless otherwise agreed in writing by the parties, SPARQ shall deliver the Products to the location identified in the Sales Confirmation (the “<strong>Delivery Point</strong>”) using SPARQ&apos;s standard methods for packaging and shipping such Products. You shall take delivery of the Products within 24 hours of SPARQ&apos;s written notice that the Products have been delivered to the Delivery Point. You shall be responsible for all unloading costs and shall provide equipment and labour reasonably suited for receipt of the Products at the Delivery Point.</li>
                            <li>SPARQ may, in its sole discretion, without liability or penalty, make partial shipments of Products to you. Each shipment will constitute a separate sale, and you shall pay for the units shipped whether such shipment is in whole or partial fulfillment of your purchase order.</li>
                            <li>If for any reason you fail to accept delivery of any of the Products on the date fixed pursuant to SPARQ&apos;s notice that the Products have been delivered at the Delivery Point, or if SPARQ is unable to deliver the Products at the Delivery Point on such date because you have not provided appropriate instructions, documents, licenses or authorizations: (i) risk of loss to the Products shall pass to you; (ii) the Products shall be deemed to have been delivered; and (iii) SPARQ, at its option, may store the Products until you pick them up, whereupon you shall be liable for all related costs and expenses (including, without limitation, storage and insurance costs).</li>
                        </ol>
                        <li><strong>Non-Delivery</strong>.</li>
                        <ol className="list-inside list-[lower-alpha]">
                            <li>The quantity of any installment of Products as recorded by SPARQ on dispatch from SPARQ&apos;s place of business is conclusive evidence of the quantity received by you on delivery unless you can provide conclusive evidence proving the contrary.</li>
                            <li>SPARQ shall not be liable for any non-delivery of Products (even if caused by SPARQ&apos;s negligence) unless you give written notice to SPARQ of the non-delivery within 10 days of the date when the Products would in the ordinary course of events have been received.</li>
                            <li>Any liability of SPARQ for non-delivery of the Products shall be limited to replacing the Products within a reasonable time or adjusting the invoice respecting such Products to reflect the actual quantity delivered.</li>
                            <li>You acknowledge and agree that the remedies set forth in this Section are your exclusive remedies for non-delivery of the Products.</li>
                        </ol>
                        <li><strong>Shipping Terms</strong>. Delivery of the Products shall be made DPA Incoterms® 2020, in accordance with the terms on the face of the Sales Confirmation.</li>
                        <li><strong>Title and Risk of Loss</strong>. Title passes to you upon the later of receipt or payment. Risk of loss passes to you on the tender of the Products to the commercial carrier. To the extent applicable, as collateral security for the payment of the purchase price of the Products, you hereby grant to SPARQ a lien on and security interest in and to all of your right, title, and interest in, to and under the Products, wherever located, and whether now existing or hereafter arising or acquired from time to time, and in all accessions thereto and replacements or modifications thereof, as well as all proceeds (including insurance proceeds) of the foregoing. The security interest granted under this provision constitutes a purchase money security interest under the Ontario <em>Personal Property Security Act</em>.</li>
                        <li><strong>Inspection and Rejection of Non-Conforming Products</strong>.</li>
                        <ol className="list-inside list-[lower-alpha]">
                            <li>You shall inspect the Products within 24 hours of receipt (“<strong>Inspection Period</strong>”). You will be deemed to have accepted the Products unless you notify SPARQ in writing of any Non-Conforming Products during the Inspection Period and furnish such written evidence or other documentation as required by SPARQ. “<strong>Non-Conforming Products</strong>” means only the following: (i) product shipped is different than identified in your purchase order; or (ii) product&apos;s label or packaging incorrectly identifies its contents.</li>
                            <li>If you timely notify SPARQ of any Non-Conforming Products, SPARQ shall, in its sole discretion, (i) replace such Non-Conforming Products with conforming Products, or (ii) credit or refund the Price for such Non-Conforming Products, together with any reasonable shipping and handling expenses incurred by you in connection therewith. You shall ship, at your expense and risk of loss, the Non-Conforming Products to SPARQ&apos;s facility. If SPARQ exercises its option to replace Non-Conforming Products, SPARQ shall, after receiving your shipment of Non-Conforming Products, ship to you, at your expense and risk of loss, the replaced Products to the Delivery Point.</li>
                            <li>You acknowledge and agree that the remedies set forth in Section 6(b) are your exclusive remedies for the delivery of Non-Conforming Products. Except as provided under Section 6(b), all sales of Products to you are made on a one-way basis and you has no right to return Products purchased under these Terms to SPARQ.</li>
                        </ol>
                        <li><strong>Price</strong>.</li>
                        <ol className="list-inside list-[lower-alpha]">
                            <li>You shall purchase the Products from SPARQ at the price(s) (the “<strong>Price</strong>”) set forth in the Sales Confirmation or, where no Price is stated in the Sales Confirmation, SPARQ&apos;s published price list in force as of that SPARQ accepts your purchase order. If the Price should be increased by SPARQ before delivery of the Products to a carrier for shipment to you, then these Terms shall be construed as if the increased price were originally inserted herein, and you shall be billed by SPARQ on the basis of such increased price.</li>
                            <li>All Prices are exclusive of all shipping charges, insurance costs, harmonized sales tax, goods and services tax, sales tax, value added tax, use and excise taxes, and any other similar taxes, duties, and charges of any kind imposed by any governmental authority on any amounts payable by you. You shall be responsible for all such charges, costs, and taxes; <em>provided that</em>, you shall not be responsible for any taxes imposed on, or with respect to, SPARQ&apos;s income, revenues, gross receipts, personnel or real or personal property, or other assets.</li>
                        </ol>
                        <li><strong>Payment Terms</strong>.</li>
                        <ol className="list-inside list-[lower-alpha]">
                            <li>You shall pay all invoiced amounts due to SPARQ within 30 days, unless agreed otherwise in advance in writing by the parties, from the date of SPARQ&apos;s invoice. You shall make all payments hereunder by conventional or electronic means, including, cash, cheque or wire transfer, and in the currency stated in the invoice.</li>
                            <li>You shall pay interest on all late payments at the lesser of the rate of 19.56% per annum or the highest rate permissible under applicable law, calculated daily and compounded monthly. You shall reimburse SPARQ for all costs incurred in collecting any late payments, including, without limitation, legal fees on a full indemnity basis. In addition to all other remedies available under these Terms or at law (which SPARQ does not waive by the exercise of any rights hereunder), SPARQ shall be entitled to suspend the delivery of any Products or your access to any Services if you fail to pay any amounts when due hereunder.</li>
                            <li>You shall not withhold payment of any amounts due and payable by reason of any set-off of any claim or dispute with SPARQ, whether relating to SPARQ&apos;s breach, bankruptcy or otherwise.</li>
                            <li>If SPARQ determines in its sole discretion that your financial condition or creditworthiness is inadequate or unsatisfactory, then in addition to SPARQ&apos;s other rights, SPARQ may without liability or penalty take any of the following actions: (i) accelerate all amounts owed by you to SPARQ under these Terms; (ii) cancel any previously accepted purchase orders; (iii) delay any further shipment of Products to you; (iv) suspend your access to the Services; and/or (v) on written notice to you, terminate these Terms.</li>
                        </ol>
                        <li><strong>Limited Warranty</strong>.</li>
                        <ol className="list-inside list-[lower-alpha]">
                            <li>SPARQ provides a limited warranty (the “<strong>Limited Warranty</strong>”) for its Products, including, but not limited to, Sparq Microinverters (models Q1200-4102 and Q2000-4102) and the SparqLinq Gateway. The terms and conditions of the Limited Warranty can be found at <a href="https://www.sparqsys.com/wp-content/uploads/2025/02/SPARQ-Limited-Warranty.pdf">SPARQ-Limited-Warranty</a> and are hereby incorporated into these Terms by reference. To make a warranty claim under this Section 9(a), you must follow the Return Merchandise Authorization (RMA) Procedure set out at <a href="https://www.sparqsys.com/warranty">sparqsys.com/warranty</a>.</li>
                            <li><strong>YOUR RIGHT TO MAKE A WARRANTY CLAIM IN ACCORDANCE WITH SECTION 9(a)</strong> <strong>SHALL BE YOUR SOLE AND EXCLUSIVE REMEDY AND SPARQ&apos;S ENTIRE LIABILITY FOR ANY BREACH OF THE LIMITED WARRANTY.</strong></li>
                        </ol>
                    </ol>
                    <p><strong><u>TERMS APPLYING TO YOUR ACCESS AND USE OF THE SERVICES</u></strong></p>
                    <ol className="list-decimal" start={10}>
                        <li><strong>Access and Use.</strong> Subject to and conditioned on your compliance with all terms and conditions of these Terms, SPARQ hereby grants you the right to access and use the Services in accordance with the terms and conditions herein.</li>
                        <li><strong>License Grant.</strong> If you access the Services via a mobile application, then we grant you a revocable, non-exclusive, non-transferable, limited right to install and use the mobile application on wireless electronic devices owned or controlled by you, and to access and use the mobile application on such devices strictly in accordance with the terms and conditions of the mobile application license contained in these Terms.</li>
                        <li>You may not copy (except as expressly permitted by these Terms), decompile, reverse-engineer, disassemble, attempt to derive the source code of, modify, or create derivative works of the Services, any updates, or any part thereof (except as and only to the extent that any foregoing restriction is prohibited by applicable law or to the extent as may be permitted by the licensing terms governing use of any open-sourced components included with the Services). Any attempt to do so is a violation of the rights of SPARQ and its licensors. If you breach this restriction, you may be subject to prosecution and damages. The terms of these Terms will govern any upgrades provided by SPARQ that replace and/or supplement the original Services, unless such upgrade is accompanied by separate terms and conditions in which case those terms will govern. SPARQ reserves all rights in and to the Services not expressly granted to you under these Terms.<strong><u>  </u></strong></li>
                        <li><strong>Apple and Android Devices</strong>. The following terms apply when you use a mobile application obtained from either the Apple Store or Google Play (each an “<strong>App Distributor</strong>”) to access the Services: (a) the license granted to you for our mobile application is limited to a non-transferable license to use the Services on a device that utilizes the Apple iOS or Android operating systems, as applicable, and in accordance with the usage rules set forth in the applicable App Distributor&apos;s terms of service; (b) we are responsible for providing any maintenance and support services with respect to the mobile application as specified in the terms and conditions of this mobile application license contained in these Terms or as otherwise required under applicable law, and you acknowledge that each App Distributor has no obligation whatsoever to furnish any maintenance and support services with respect to the mobile application; (c) in the event of any failure of the mobile application to conform to any applicable warranty, you may notify the applicable App Distributor, and the App Distributor, in accordance with its terms and policies, may refund the purchase price, if any, paid for the mobile application, and to the maximum extent permitted by applicable law, the App Distributor will have no other warranty obligation whatsoever with respect to the mobile application; (d) you represent and warrant that (i) you are not located in a country that is subject to a Canadian or U.S. government embargo, or that has been designated by the Canadian or U.S. government as a “terrorist supporting” country and (ii) you are not listed on any Canadian or U.S. government list of prohibited or restricted parties; (e) you must comply with applicable third-party terms of agreement when using the mobile application; and (f) you acknowledge and agree that the App Distributors are third-party beneficiaries of the terms and conditions in the mobile application license contained in these Terms, and that each App Distributor will have the right (and will be deemed to have accepted the right) to enforce the terms and conditions of the mobile application license contained in these Terms against you as a third-party beneficiary thereof.</li>
                        <li><strong>Account Registration.</strong> You may be required to register to use all or part of the Services. You agree that all information that you provide to us is true, accurate and complete and that you will maintain and update such information as necessary. We may reject, or require that you change, any registration or other information that you provide to us. Your account is for your personal use only, and your registration information should be kept confidential. You are responsible for any use or misuse of your account, and you must promptly notify us of any confidentiality breach or unauthorized use of your registration information or account. You agree not to transfer your registration information or lend or otherwise transfer your use of or access to the Services, to any third party.</li>
                        <li><strong>User Content.</strong></li>
                        <ol className="list-inside list-[lower-alpha]">
                            <li>The nature of the Services involves the transmission of data. Although you retain copyright and any other rights you already hold in or to any information (such as photographs, videos or other images, written text, audio files or other sounds) which you submit, post or display on or through the Services (collectively, “<strong>Content</strong>”), by submitting the Content you give SPARQ a perpetual, irrevocable, worldwide, royalty-free, and non-exclusive license to reproduce, adapt, modify, translate, publish, publicly perform, publicly display, act on and distribute such Content for purposes consistent with the intended use of the Services.  In addition, when you use the Services and if you have enabled &apos;location services&apos; permission for the Services, the Services automatically transfers location data to SPARQ.</li>
                            <li>By submitting Content, you represent and warrant that you own or have the necessary rights to submit the Content and to grant the above license and that you will comply with all applicable laws, including privacy laws, when uploading, sharing, or posting Content.</li>
                            <li>You agree that SPARQ may collect and use technical data and related information, including but not limited to technical information about your device, system and application software, and peripherals, that is gathered periodically to facilitate the provision of software updates, product support, and other services to you (if any) related to the Services. SPARQ may use the information provided, as long as it is in a form that does not personally identify you, to improve its products or to provide services or technologies to you.</li>
                            <li>The Content may be stored on cloud servers located outside Canada. In such instance, the Content and access thereto shall be governed by the laws of such jurisdiction which may be different than those in Canada, including additional access rights of government institutions to the Content.  Given the communication channels inherent in data flow, Content may flow through communication channels and our communication partners&apos; servers in connection with the provision of the Services.  You understand that, in performing the required technical steps to provide the Services to our users, we may, (i) transmit or distribute Content over various public networks and in various media; and (ii) make such changes to Content as are necessary to conform and adapt Content to the technical requirements of connecting networks, devices, services or media. You agree that these Terms shall permit SPARQ to take these actions.</li>
                        </ol>
                        <li><strong>Privacy Policy.</strong> SPARQ is committed to protecting your privacy. The collection, storage, use and disclosure of your personal information is governed by our Privacy Policy, which can be found at www.sparqsys.com/privacy. By accessing or using the Services, you consent to the collection, use and disclosure of your personal information as outlined in our Privacy Policy.</li>
                        <li><strong>Termination and Suspension of Services</strong>. You may terminate your account at any time upon written notice to SPARQ. If you wish to terminate, please provide notice by using SPARQ&apos;s contact support page. SPARQ reserves the right to change, suspend, remove, or disable access to any Services at any time without notice. In no event will SPARQ be liable for the removal of or disabling of access to any such Services. SPARQ may also impose limits on the use of or access to such Services, in any case and without notice or liability. Upon termination of these Terms, you shall cease all use of the Services.  SPARQ reserves the right to modify, suspend, or discontinue the Services (or any part thereof) at any time.  While SPARQ may attempt to provide notice to you of the termination, there may be instances where such notice of termination is not reasonably possible.  SPARQ will not be liable to you or to any third party should SPARQ exercise such right to termination in the aforementioned manner.</li>
                        <li><strong>Third Party Materials. </strong>The Services may display, include or make available content, data, information, applications or materials from third parties (“<strong>Third Party Materials</strong>”) or provide links to certain third party websites. By using the Services, you acknowledge and agree that neither SPARQ, nor any third party is responsible for examining or evaluating the content, accuracy, completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect of Third Party Materials or websites. You agree that SPARQ and its officers, affiliates and subsidiaries do not warrant or endorse, and will not have any liability or responsibility to you or any other person for Third Party Materials or websites, or for any other materials, products, or services of third parties. Third Party Materials and links to other websites are provided solely as a convenience to you.</li>
                        <li><strong>Acknowledgement of Certain Limitations. </strong>You acknowledge that, (a) you will not receive any notifications from the Services if your device is turned off, in airplane mode, or is outside of cellular or Wi-Fi service range; (b) any notifications from the Services may be incomplete or inaccurate; (c) any guidance provided by the Services may not be suitable for your situation; (d) you must use your reasonable personal judgment to determine the appropriate action to take upon receiving a notification from the Services; (e) we have the right to report all false or inappropriate reports and/or potentially fraudulent, dangerous or illegal use of the Services to law enforcement and we will cooperate fully with law enforcement in investigating the use of the Services; and (g) filing false reports or otherwise misusing the Services may lead to civil and/or criminal prosecution.</li>
                        <li><strong>Inappropriate Use of the Services.</strong> You agree not to use the Services in any manner to harass, abuse, stalk, threaten, defame or otherwise infringe or violate the rights of any other party.  You further agree not to use the Services for any illegal purposes or in any manner that is contrary to the law.  SPARQ is not in any way responsible for any such use by you, nor for any harassing, threatening, defamatory, offensive, infringing or illegal messages or transmissions that you may receive as a result of using the Services.</li>
                        <li><strong>Access</strong> In addition, the Services are not available in all languages or in all countries or regions. SPARQ makes no representation that the Services are appropriate or available for use in any particular location. To the extent you choose to use or access the Services, you do so at your own initiative and risk, and are responsible for compliance with any applicable laws, including but not limited to applicable local laws. SPARQ reserves the right to change, suspend, remove, or disable access to any Services at any time without notice. In no event will SPARQ be liable for the removal of or disabling of access to any such Services. SPARQ may also impose limits on the use of or access to the Services, in any case and without notice or liability.</li>
                        <li><strong>Intellectual Property Rights &amp; Protection. </strong>SPARQ respects the intellectual property of others and requires that users of the Services do the same. You agree that the Services contain proprietary content, information and material that is owned by SPARQ and/or its licensors, and is protected by applicable intellectual property and other laws, including but not limited to copyright, and that you will not use such proprietary content, information or materials in any way whatsoever or in any manner that is inconsistent with the terms of these Terms or that infringes any intellectual property rights of a third party except for permitted use of the Services. No portion of the Services may be reproduced in any form or by any means. You agree not to modify, rent, lease, loan, sell, distribute, or create derivative works based on the Services, in any manner, and you shall not exploit the Services in any unauthorized way whatsoever, including but not limited to, using the Services to transmit any computer viruses, worms, trojan horses or other malware, or by trespass or burdening network capacity. When you use the Services, you may not upload, store, share, display, post, e-mail, transmit or otherwise make available any material that infringes any copyright, patent, trademark, trade secret or other proprietary rights of any person or entity. In appropriate circumstances, SPARQ will terminate the accounts of repeat infringers.</li>
                    </ol>
                    <p><strong><u>GENERAL TERMS</u></strong></p>
                    <ol className="list-decimal" start={23}>
                        <li><strong>Disclaimer</strong>.</li>
                        <ol className="list-inside list-[lower-alpha]">
                            <li><strong>EXCEPT FOR THE EXPRESS WARRANTIES SET FORTH IN SECTION 9(a), ALL PRODUCTS AND SERVICES ARE PROVIDED “AS IS” AND SPARQ HEREBY DISCLAIMS ALL CONDITIONS AND WARRANTIES, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE UNDER THESE TERMS, AND SPARQ SPECIFICALLY DISCLAIMS ALL IMPLIED CONDITIONS AND WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT, AND ALL WARRANTIES ARISING FROM COURSE OF DEALING, USAGE, OR TRADE PRACTICE. WITHOUT LIMITING THE FOREGOING, SPARQ MAKES NO CONDITION OR WARRANTY OF ANY KIND THAT THE PRODUCTS OR SERVICES, OR ANY PRODUCTS OR RESULTS OF THE USE THEREOF, WILL (a) MEET YOUR OR ANY OTHER PERSON&apos;S REQUIREMENTS; (b) OPERATE WITHOUT INTERRUPTION; (c) ACHIEVE ANY INTENDED RESULT; (d) BE COMPATIBLE OR WORK WITH ANY SOFTWARE, SYSTEM, OR OTHER SERVICES; OR (e) BE SECURE, ACCURATE, COMPLETE, FREE OF HARMFUL CODE, OR ERROR FREE. </strong></li>
                            <li>Products and materials manufactured by a third party may constitute, contain, be contained in, incorporated into, attached to, or packaged together with, the Products or Services. Such third-party products and services are not covered by the warranty in Section 9(a). For the avoidance of doubt, <strong>ALL THIRD-PARTY PRODUCTS AND MATERIALS ARE PROVIDED “AS IS” AND ANY REPRESENTATION OR WARRANTY OF OR CONCERNING ANY THIRD-PARTY PRODUCTS OR MATERIALS IS STRICTLY BETWEEN YOU AND THE THIRD-PARTY OWNER OR DISTRIBUTOR OF THE THIRD-PARTY PRODUCTS OR MATERIALS.</strong></li>
                            <li><strong>SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES OR LIMITATIONS ON APPLICABLE STATUTORY RIGHTS OF A CONSUMER, SO THE ABOVE EXCLUSION AND LIMITATIONS MAY NOT APPLY TO YOU.</strong></li>
                        </ol>
                        <li><strong>Limitation of Liability</strong>.</li>
                        <ol className="list-inside list-[lower-alpha]">
                            <li><strong>IN NO EVENT SHALL SPARQ BE LIABLE FOR ANY CONSEQUENTIAL, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR PUNITIVE DAMAGES, LOST PROFITS OR REVENUES, OR DIMINUTION IN VALUE, ARISING OUT OF OR RELATING TO ANY BREACH OF THESE TERMS, WHETHER OR NOT THE POSSIBILITY OF SUCH DAMAGES HAS BEEN DISCLOSED IN ADVANCE OR COULD HAVE BEEN REASONABLY FORESEEN, REGARDLESS OF THE LEGAL OR EQUITABLE THEORY (CONTRACT, TORT, OR OTHERWISE) UPON WHICH THE CLAIM IS BASED, AND NOTWITHSTANDING THE FAILURE OF ANY AGREED OR OTHER REMEDY OF ITS ESSENTIAL PURPOSE.</strong></li>
                            <li><strong>IN NO EVENT SHALL SPARQ&apos;S AGGREGATE LIABILITY ARISING OUT OF OR RELATED TO THESE TERMS, WHETHER ARISING OUT OF OR RELATED TO BREACH OF CONTRACT, TORT (INCLUDING NEGLIGENCE) OR OTHERWISE, EXCEED THE TOTAL OF THE AMOUNTS PAID TO SPARQ FOR ANY PRODUCTS SOLD UNDER AN APPLICABLE SALES CONFIRMATION.</strong></li>
                        </ol>
                        <li><strong>Indemnification</strong>. By purchasing Products or using the Services, you agree to indemnify and hold SPARQ, and its directors, officers, employees, affiliates, agents, and licensors harmless with respect to any claims arising out of your breach of these Terms or your use of the Products or Services.</li>
                        <li><strong>Compliance with Law</strong>. You shall comply with all applicable laws, regulations, and ordinances. You shall maintain in effect all the licenses, permissions, authorizations, consents, and permits that you need to carry out your obligations under these Terms. You shall comply with all export and import laws of all countries involved in the sale of the Products under these Terms or any resale of the Products by you. You assume all responsibility for shipments of Products requiring any government import clearance.</li>
                        <li><strong>Your Acts or Omissions</strong>. If SPARQ&apos;s performance of its obligations under these Terms is prevented or delayed by any act or omission of you or your agents, subcontractors, consultants or employees, SPARQ shall not be deemed in breach of its obligations under these Terms or otherwise liable for any costs, charges, or losses sustained or incurred by you, in each case, to the extent arising directly or indirectly from such prevention or delay.</li>
                        <li><strong>Termination</strong>. In addition to any remedies that may be provided under these Terms, SPARQ may terminate these Terms with immediate effect upon written notice to you, if you: (a) fail to pay any amount when due under these Terms; (b) have not otherwise performed or complied with any of these Terms, in whole or in part; or (c) become insolvent, file a petition for bankruptcy or commence or have commenced against you proceedings relating to bankruptcy, receivership, liquidation, reorganization, or assignment for the benefit of creditors.</li>
                        <li><strong>Waiver</strong>. No waiver by SPARQ of any of the provisions of these Terms is effective unless explicitly set forth in writing and signed by SPARQ. No failure to exercise, or delay in exercising, any right, remedy, power or privilege arising from these Terms operates, or may be construed, as a waiver thereof. No single or partial exercise of any right, remedy, power or privilege hereunder precludes any other or further exercise thereof or the exercise of any other right, remedy, power or privilege.</li>
                        <li><strong>Confidential Information</strong>. All non-public, confidential or proprietary information of SPARQ, including but not limited to, specifications, samples, patterns, designs, plans, drawings, documents, data, business operations, customer lists, pricing, discounts or rebates, disclosed by SPARQ to you, whether disclosed orally or disclosed or accessed in written, electronic or other form or media, and whether or not marked, designated or otherwise identified as “confidential” in connection with these Terms is confidential, solely for the use of performing these Terms and may not be disclosed or copied unless authorized in advance by SPARQ in writing. Upon SPARQ&apos;s request, you shall promptly return all documents and other materials received from SPARQ. SPARQ shall be entitled to injunctive relief for any violation of this Section. This Section does not apply to information that is: (a) in the public domain; (b) known to you at the time of disclosure; or (c) rightfully obtained by you on a non-confidential basis from a third party.</li>
                        <li><strong>Ownership of Intellectual Property Rights</strong>. You acknowledge and agree that: (a) any and all SPARQ intellectual property rights are the sole and exclusive property of SPARQ or its licensors; (b) you shall not acquire any ownership interest in any of SPARQ&apos;s intellectual property rights under these Terms; (c) any goodwill derived from the use by you of SPARQ&apos;s intellectual property rights enures to the benefit of SPARQ or its licensors, as the case may be; (d) if you acquire any intellectual property rights, rights in or relating to any Products or Services (including any rights in any trademarks, derivative works, or patent improvements relating thereto) by operation of law, or otherwise, such rights are deemed and are hereby irrevocably assigned to SPARQ or its licensors, as the case may be, without further action by either of the parties; and (e) you shall use SPARQ&apos;s intellectual property rights solely for purposes of using the Products and accessing the Services under these Terms and only in accordance with these Terms and the instructions of SPARQ.</li>
                        <li><strong>Force Majeure</strong>. SPARQ shall not be liable or responsible to you, nor be deemed to have defaulted under or breached these Terms, for any failure or delay in fulfilling or performing any term of these Terms, when and to the extent such SPARQ&apos;s failure or delay is caused by or results from the following force majeure events: (a) acts of God; (b) flood, tsunami, fire, earthquake, explosion; (c) epidemics, pandemics; (d) war, invasion, hostilities (whether war is declared or not), terrorist threats or acts, riot, or other civil unrest; (e) government order, law or actions; (f) embargoes or blockades in effect on or after the date of these Terms; (g) national or regional emergency; (h) strikes, lockouts, labour stoppages or slowdowns, labour disputes, or other industrial disturbances; (i) shortage of adequate power or telecommunications or transportation facilities; (j) failure of any governmental or public authority to grant a necessary licence or consent; and (k) other events beyond the control of SPARQ.</li>
                        <li><strong>Assignment</strong>. You shall not assign any of your rights or delegate any of your obligations under these Terms without the prior written consent of SPARQ. Any purported assignment or delegation in violation of this Section is null and void. No assignment or delegation relieves you of any of your obligations under these Terms.</li>
                        <li><strong>Relationship of the Parties</strong>. The relationship between the parties is that of independent contractors. Nothing contained in these Terms shall be construed as creating any agency, partnership, joint venture, or other form of joint enterprise, employment, or fiduciary relationship between the parties, and neither party shall have authority to contract for or bind the other party in any manner whatsoever.</li>
                        <li><strong>No Third-Party Beneficiaries</strong>. Except as set out in Section 25, these Terms are for the sole benefit of the parties hereto and their respective successors and permitted assigns and nothing herein, express or implied, is intended to or shall confer upon any other person or entity any legal or equitable right, benefit or remedy of any nature whatsoever under or by reason of these Terms.</li>
                        <li><strong>Governing Law</strong>. All matters arising out of or relating to these Terms are governed by and construed in accordance with the laws of the Province of Ontario and the federal laws of Canada applicable therein without giving effect to any choice or conflict of law provision or rule. The United Nations Convention on Contracts for the International Sale of Products does not apply to these Terms.</li>
                        <li><strong>Choice of Forum</strong>. Any legal suit, action, litigation, or proceeding of any kind whatsoever in any way arising out of, from, or relating to these Terms, including all exhibits, schedules, attachments, and appendices attached to these Terms, and all contemplated transactions, shall be instituted in the courts of the Province of Ontario, and each party irrevocably submits to the exclusive jurisdiction of such courts in any such suit, action, litigation, or proceeding. Service of process, summons, notice, or other document by mail to such party&apos;s address set forth herein shall be effective service of process for any suit, action, litigation, or other proceeding brought in any such court. Each party agrees that a final judgment in any such suit, action, litigation, or proceeding is conclusive and may be enforced in other jurisdictions by suit on the judgment or in any other manner provided by law. The Parties irrevocably and unconditionally waive any objection to the venue of any action or proceeding in such courts and irrevocably waive and agree not to plead or claim in any such court that any such action or proceeding brought in any such court has been brought in an inconvenient forum.</li>
                        <li><strong>Notices</strong>. Each party shall deliver all notices, requests, consents, claims, demands, waivers, and other communications under these Terms (other than routine communications having no legal effect) (each, a “<strong>Notice</strong>”) in writing and addressed to the parties at the addresses set forth on the face of the Sales Confirmation (or to such other address that may be designated by the receiving party from time to time in accordance with this Section). Notices sent in accordance with this Section will be conclusively deemed validly and effectively given: (a) on the date of receipt, if delivered by personal delivery, or by a nationally recognized same day or overnight courier (with all fees prepaid); (b) upon the sender&apos;s receipt of an acknowledgment from the intended recipient (such as by the “read receipt” function, as available, return email or other form of written acknowledgment), if delivered by email; or (c) on the third day after the date mailed by certified or registered mail, return receipt requested, postage prepaid.</li>
                        <li><strong>Severability</strong>. If any term or provision of these Terms is invalid, illegal, or unenforceable in any jurisdiction, such invalidity, illegality, or unenforceability shall not affect any other term or provision of these Terms or invalidate or render unenforceable such term or provision in any other jurisdiction.</li>
                        <li><strong>Survival</strong>. Provisions of these Terms which by their nature should apply beyond their terms will remain in force after any termination or expiration of these Terms.</li>
                    </ol>
                    <div className="bg-brand-maroon p-2 rounded-xl border-2 border-brand-yellow text-gray-200">
                        <h3 className="text-black underline font-bold">QUESTIONS AND CONCERNS</h3>
                        <p>For questions or concerns about these Terms, please contact SPARQ at:</p>
                        <Link href="https://maps.app.goo.gl/VF6abo1QMnPYKq1M7" target="_blank">
                            <p>Sparq Systems Incorporated<br />Innovation Park, 945 Princess Street,<br />Kingston, Ontario, CANADA K7L 0E9<br /></p>
                        </Link>
                        <a href="tel:1-343-477-1158">Phone: 1-343-477-1158</a><br></br>
                        <a href="mailto:support@Sparqsys.com">Email: support@Sparqsys.com</a>
                        <p>Website: <Link target="_blank" href="https://www.sparqsys.com">www.sparqsys.com</Link></p>
                    </div>
                </div>
            )
            }
        </div >
    )
}